dts_luxury_transport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('passenger.urls')),
    #path('users/', include('users.urls', namespace="users")),
    path('users/', include('user_base.urls', namespace="users")),
    path('rentals/', include('rentals.urls', namespace="rentals")),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),      

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

passenger/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name="home"),
    path('next/', views.part_one, name="home_pt_2"),
    path('final/', views.final, name="home_final"),
    path('confirm_booking/', views.active_booking, name="booked"),
    path('select_car/', views.select_car, name="select_car"),

    path('payment/', views.payment, name="payment"),
    path('webhook/', views.stripe_webhook),

    path('gallery', views.galleryPage, name="gallery"),
    path('home_subcribe', views.home, name="home_subcribe"),
    path('contact', views.contact, name='contact')
]

rentals/urls.py
from django.urls import path, re_path
from . import views


app_name = "rentals"
urlpatterns = [
	path('cars_for_rents/', views.rents, name="rents"), #rents_detail
	path('webhook/', views.stripe_webhook), #rents_detail
	#path('car_forms/<slug:car_id>/<slug:user_id>/', views.proceed_rent, name='proceed_payment'), 
	path('cars_details/<slug:id>', views.rents_det, name="rents_detail"), 
	re_path(r'^car_forms/(?P<slug>[\w-]+)/(?P<user>[\w-]+)/$',views.proceed_rent, name="proceed_payment"),
]

user_base/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views	
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm #,PwdResetForm,PwdResetConfirmForm


app_name = "users"
urlpatterns = [
    
	path('sign-in/', auth_views.LoginView.as_view(template_name='user/sign_in.html', form_class=UserLoginForm), name='sign-in'),
    
    path('sign-out/', auth_views.LogoutView.as_view(next_page='/users/sign-in'), name='sign-out'),
	
	#path('account/', views.AccountView.as_view(), name="account"),
	path('profile/', views.dashboard, name="profile"),
	path('sign-up/', views.account_register, name="sign-up"),
	path('profile/edit/', views.profile_edit, name="edit_profiles"),
	path('profile/delete/', views.delete_user, name="delete_user"),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="user/delete_confirm.html"), name='delete_confirmation'),
	path('activate/<slug:uidb64>/<slug:token>', views.account_activate, name="activate"),
    path("password_reset", views.password_reset_request, name="password_reset"),
]

passenger/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.conf import settings
from .models import BookingDB, Subscriber, ContactFeedback, BookingDb_part2, BookngDb_final, CarsAvailable, Active_Bookings, Carselection, Active_orders
from django.conf import settings
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.http.response import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail

import json

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
import uuid
import stripe
# Create your views here.



def homePage(request):
    if request.method == "POST":
        service_details = request.POST['service_details']
        pick_up_date = request.POST['pick_up_date']
        pick_up_time_hour = request.POST['pick_up_time']
        number_of_passenger = request.POST['number_of_passenger']
        number_of_luggages = request.POST['number_of_luggages']
        

        session_uuid = uuid.uuid4()
        booking_id = session_uuid
        
        request.session['booking_id'] = str(booking_id)
        print(booking_id)
        r = request.session.get('booking_id')
        print(r)


        #
        bookingForm = BookingDB.objects.get_or_create(
            service_details = service_details, 
            pick_up_date = pick_up_date,
            pick_up_time = pick_up_time_hour,
            number_of_passenger = number_of_passenger, 
            number_of_luggages = number_of_luggages,
            booking_id = booking_id
        )
        messages.info(request, "let's proceed")
        print('Booking saved')

        

        paths = '/select_car/'
        print (paths)
        return redirect(paths)
        
    context = {
	    "google_api_key": settings.GOOGLE_API_KEY,
        "base_country": settings.BASE_COUNTRY
        }
    return render(request, 'passenger/index.html', context)

def part_one(request):
    s = request.session.get('booking_id')
    product = BookingDB.objects.filter(booking_id=s).order_by('-date').first()
    car_available = CarsAvailable.objects.filter(booked=False )
    #product = get_object_or_404(BookingDB, booking_id=s,).order_by('-date').first()
    if request.method == "POST":
        pick_up_address = request.POST.get('pick_up_address', False)
        dropoff_address = request.POST.get('google_address_b', False)
        pickup_airport = request.POST.get('pickup_airport',False)
        dropoff_airport = request.POST.get('dropoff_airport', False)
        distance = request.POST.get('distance', False)
        airline = request.POST.get("airline", False)
        work_hour = request.POST.get('work_hour', False)
        flight_number = request.POST.get('flight_number', False)
        booking_id = s


        BookingDb_part2.objects.get_or_create( pick_up_address = pick_up_address, 
                dropoff_address = dropoff_address,
                pickup_airport = pickup_airport,
                dropoff_airport = dropoff_airport,
                distance = distance,
                airline = airline,
                work_hour = work_hour,
                flight_number = flight_number,
                booking_id=booking_id)


        paths = '/final/'
        print (paths)
        return redirect(paths)
        
        

    context = {'books_p': product, 'car_a': car_available, 's':s}
    return render(request, 'passenger/select.html', context)
        

def final(request):
    s = request.session.get('booking_id')
    product = BookingDb_part2.objects.filter(booking_id=s).order_by('-date').first()
    print(product)
    
    print(product.booking_id)
    if request.method == "POST":
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phone_number = request.POST['phone_number']
        email = request.POST['email']

        booking_id = s


        BookngDb_final.objects.get_or_create(
                first_name = first_name,
                last_name = last_name,
                phone_number = phone_number,
                email = email,
                booking_id = booking_id
                ) #confirm_booking
        
        paths = '/confirm_booking/'
        print (paths)
        return redirect(paths)
    context = {'user_det': product}
    return render(request, 'passenger/user_details.html', context)


def select_car(request):
    s = request.session.get('booking_id')
    c = CarsAvailable.objects.filter(booked=False)

    if request.method == 'POST':
        car_id = request.POST['car_id']
        booking_id = s

        Carselection.objects.get_or_create(
            car_id = car_id,
            booking_id = booking_id
        )

        paths = '/next/'
        print (paths)
        return redirect(paths)


    context = {'c': c}
    return render(request, 'passenger/select_car.html', context)


        


def active_booking(request):
    s = request.session.get('booking_id')
    part_one =  BookingDB.objects.filter(booking_id=s).order_by('-date').first()
    part_two =  BookingDb_part2.objects.filter(booking_id=s).order_by('-date').first()
    part_three =  BookngDb_final.objects.filter(booking_id=s).order_by('-date').first()
    car_s = Carselection.objects.filter(booking_id=s).order_by('-date').first()
    car_a = CarsAvailable.objects.filter(id=car_s.car_id).first()


    if request.method == 'POST':
        first_name = part_three.first_name
        last_name = part_three.last_name
        phone_number = part_three.phone_number
        email = part_three.email
        service_details = part_one.service_details
        pick_up_date = part_one.pick_up_date
        pick_up_time = part_one.pick_up_time
        number_of_passenger = part_one.number_of_passenger
        number_of_luggages = part_one.number_of_luggages
        pick_up_address = part_two.pick_up_address
        dropoff_address = part_two.dropoff_address
        dropoff_airport = part_two.dropoff_airport
        pickup_airport = part_two.pickup_airport
        distance = part_two.distance
        work_hour = part_two.work_hour
        flight_number = part_two.flight_number
        car_name = car_a.car_name
        boking_per_hour = car_a.boking_per_hour
        price = car_a.price
        payment = request.POST['payment']
        print(car_name)
        car_model = car_a.car_model

        booking_id = s

        Active_Bookings.objects.get_or_create(
            first_name = first_name,
            last_name = last_name,
            phone_number = phone_number,
            email = email,
            service_details = service_details,
            pick_up_date = pick_up_date,
            pick_up_time = pick_up_time,
            number_of_passenger = number_of_passenger,
            number_of_luggages = number_of_luggages,
            pick_up_address = pick_up_address,
            dropoff_address = dropoff_address,
            dropoff_airport = dropoff_airport,
            pickup_airport = pickup_airport,
            distance = distance,
            work_hour = work_hour,
            flight_number = flight_number,
            car_name = car_name,
            car_model = car_model,
            payment = payment,
            boking_per_hour = boking_per_hour,
            price = price,

            booking_id = booking_id
            
        )

        paths = '/payment/'
        print (paths)
        return redirect(paths)
    
    context = {'p1': part_one, 'p2': part_two, 'p3': part_three, 'ca': car_a}
    return render(request, 'passenger/overview.html', context)


def payment(request):
    s = request.session.get('booking_id')
    active_p =  Active_Bookings.objects.filter(booking_id=s).order_by('-date').first()
    ire = active_p.calculate_total_book_hrs()
    print(ire)
    print(type(ire))

    res = ire * 100

    if request.POST.get('action') == 'POST':
        order_key = request.POST.get('order_key')
        active = Active_orders.objects.create(order_key=order_key, booking_id=s)


    stripe.api_key = 'sk_test_51MlxVxA82DOnA7aGjkIu860CpiBrititfiqNFpWCqShjdquSvRL3NJq1Yumk5lmvMsNnE5A94zMPAinZzGISg2IU00bCF3uMPR'
    intent = stripe.PaymentIntent.create( amount=res, currency='usd', metadata={'userid': s})
    context = {'rents': active_p, 'client_secret': intent.client_secret, 'ire':ire} #
    
    return render(request, 'rentals/book_form.html', context)

@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    event = None

    try:
        event = stripe.Event.construct_from(
            json.loads(payload), stripe.api_key
        )
    except ValueError as e:
        print(e)
        return HttpResponse(status=400)

    # Handle the event
    if event.type == 'payment_intent.succeeded':
        payment_confirmation(event.data.object.client_secret)

    else:
        print('Unhandled event type {}'.format(event.type))

    return HttpResponse(status=200)

def payment_confirmation(data):
    Active_orders.objects.filter(order_key=data).update(billing_status=True)



#subcriber logic for newsletter
# Helper Functions
def home(request):
    if request.method == "POST":
        #get the email from the input field
        email = request.POST['email']

        #if already a subcriber dont notify and dont safe
        if Subscriber.objects.filter(email=email).first():
            messages.error(request, f'{email} is already a subcriber')
            return redirect('home_subcribe')
        
        try:
            validate_email(email)
        except ValidationError as e:
            messages.error(request, e.messages[0])
            print('Error')
            return redirect("home_subcribe")
        
        #if pass all condition save to the database
        subcriber,_ = Subscriber.objects.get_or_create(email=email)
        message = Mail(
            from_email=settings.FROM_EMAIL,
            to_emails=[subcriber.email],

passenger/templates/user/activation_invalid.html
{% extends 'home.html'%}
{% load static %}

{% block home_form_one%}
invalid link.
{% endblock %}


{% block content %}

<section>
<p>
    the activation link is invalid ....
</p>

<p>
    pls contact the admin ... 
</p>
</section>
{% endblock%}

passenger/templates/user/dashboard.html
{% extends 'home.html' %}
{% load static %}

{% block home_form_one%}
Dashboard.
{% endblock %}


{% block content %}
<style>
    section.user_p {
        font-size: 2rem;
        color: #444;
    }
    .styled-table {
        border-collapse: collapse;
        width: 100%;
        font-size: 1.8rem;
        font-family: sans-serif;
        color: #444;
        margin: 1em 0;
        text-align: center;
      }
      
      .styled-table td {
        padding: 0.5em;
        border-bottom: 1px solid #ddd;
      }
      
      .styled-table tr:nth-of-type(even) {
        background-color: #f9f9f9;
      }
      
      .styled-table tr:last-of-type {
        border-bottom: 2px solid #c89f6b;
      }
      
      .left-column {
        text-align: left;
        width: 35%;
      }
      
      .right-column {
        text-align: left;
        width: 65%;
      }
      
      
</style>

<section class="user_p">
    welcome, {{users.first_name }}

    <table class="styled-table">
        <tr>
          <td class="left-column">First name:</td>
          <td class="right-column"> {{users.first_name }}</td>
        </tr>
        <tr>
          <td class="left-column">last name:</td>
          <td class="right-column"> {{users.last_name }}</td>
        </tr>
        <tr>
          <td class="left-column">phone number:</td>
          <td class="right-column"> {{users.phone_number }}</td>
        </tr>
        <tr>
          <td class="left-column">email:</td>
          <td class="right-column"> {{users.email}}</td>
        </tr>
        <tr>
          <td class="left-column">username:</td>
          <td class="right-column"> {{users.user_name}}</td>
        </tr>
      </table>

      do you want to <a href="/users/profile/edit/">Edit your profile?</a>
      
      
      
      
</section>

{% endblock %}

passenger/templates/user/delete_confirm.html
{% extends 'home.html'%}
{% load static %}
{% block home_form_one%}
Account Deleted. 
{% endblock %}

{% block content %}

<section>
    <p>
        your account have been deleted....
    </p>
</section>

{% endblock%}

passenger/templates/user/edit_profile.html
{% extends 'home.html'%}
{% load static %}

{% block home_form_one%}
Edit profile
{% endblock %}

{% block css_one %}
<link rel='stylesheet' href="{% static 'user_profie.css'%}"/>

{% endblock%}

{% block content %}

<section class="body">
      <div class="body_container">
        <div class="title">Update Profile </div>
        <div class="content">
          <form action="{%url 'users:edit_profiles'%}" enctype="multipart/form-data" method="post">

            {% if user_form.is_valid  %}
            <div class="alert green">
              Details succefully updated
            </div>

            {% else %}
            <p>
              change your details
            </p>
            {% endif %}

            {% if form.error %}
            <div class="alert">
              Error: please try again
            </div>
            {% endif%}

            {% csrf_token%}
            <div class="user-details">
              <div class="input-box">
                <span class="details">Email</span>
                {{user_form.email}}
              </div>
              <div class="input-box">
                <span class="details">Username</span>
                {{user_form.user_name}}
              </div>
              <div class="input-box">
                <span class="details">first Name </span>
                {{user_form.first_name}}
              </div>
              <div class="input-box">
                <span class="details">Last Name </span>
                {{user_form.last_name}}
              </div>
              <div class="input-box">
                <span class="details">Phone Number</span>
                {{ user_form.phone_number}}
              </div>
            </div>
            <div class="button">
              <input type="submit" value="Update">
            </div>
            <div class="input-box">
                <span class="details">Delete Profile <a href="/users/profile/delete/"> click here to delete your account</a></span>
              </div>
          </form>
        </div>
      </div>
    

    
</section>



{% endblock%}

passenger/templates/user/password_reset.html
{% extends 'home.html' %}
{% load static %}
{% block home_form_one%}
Reset password
{% endblock %}
{% block css_one %}
<link rel="stylesheet" href="{% static 'passenger/style.css'%}" />
{% endblock %}
{% block css_two %}
<style>
  .check_box {
    height: auto !important;
  }

  .alert {
    display: block;
    font-weight: bolder;
    color: red;
  }

  ul,
  li {
    list-style: none;
  }
</style>
{% endblock %}



{% block content %}
{% if request.user.is_authenticated %}
<script>
  window.location.href = '{% url "users:profile" %}';
</script>
{% endif %}




<div class="sign_up_body">
	<div class="container">
	  <input type="checkbox" id="flip">
	  <div class="cover">
		<div class="front">
		  <img src="{% static 'passenger/images/frontImg.jpg'%}" alt="">
		  <div class="text">
			<span class="text-1">Every new friend is a <br> new adventure</span>
			<span class="text-2">Let's get connected</span>
		  </div>
		</div>
		<div class="back">
		  <img class="backImg" src="{% static 'passenger/images/backImg.jpg' %}" alt="">
		  <div class="text">
			<span class="text-1">Complete miles of journey <br> with one step</span>
			<span class="text-2">Let's get started</span>
		  </div>
		</div>
	  </div>
	  <div class="forms">
		<div class="form-content">
		  <div class="login-form">
			<div class="title">Reset Password</div>
			
	<p> Forgotten Your Password? Enter Your Email Address Below, And We'll Email Instructions For Setting A New One.</p>
			<form action="{% url "users:password_reset"%}" id="signinformw" method="POST">
			  {% if form.errors %}
  
			  <p>
				Please correct the following errors:
			  </p>
			  {% for field in form %}
			  {% if field.errors %}
			  <div class="alert">
				{{field.label}}: {{field.errors|striptags}}
			  </div>
			  {% endif %}
			  {% endfor %}
			  <p>
				if the error continues,please contact the admin
			  </p>
			  {% endif %}
			  {% csrf_token %}
			  <div class="input-boxes">
				<div class="input-box">
				  <i class="fas fa-envelope"></i>
				  {{ password_reset_form.email }}    
				</div>
  
				<!--<div class="text"><a href="#">Forgot password?</a></div>-->
  
				<div class="button input-box">
				  <input type="submit" value="Send Email">
				</div>
  
				<div class="text sign-up-text">Don't have an account? <a href="/users/sign-up/" class="label"> Signup
					now</a>
				  <!--<label for="flip">Sigup now</label>-->
				</div>
			  </div>
  
			</form>
		  </div>
		  <div class="signup-form">
		  </div>
		</div>
	  </div>
	</div>
  </div>






















{% endblock %}

	<!--Reset Password-->
	<div class="container p-5">
		<h2 class="font-weight-bold mt-3">Reset Password</h2>
	 <hr>
	 <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
	 <form method="POST">
		 {% csrf_token %}
		 {{ password_reset_form.email }}                    
		 <button class="btn btn-primary" type="submit">Send email</button>
	 </form>
   </div> 

passenger/templates/user/password_reset_confirm.html
{% extends 'home.html'%}
{% load static %}
{% block css_one %}
<link rel="stylesheet" href="{% static 'passenger/style.css'%}" />
{% endblock %}

{% block css_two %}
<style>
  .check_box {
    height: auto!important;
  }

  .alert {
    display: block;
    font-weight: bolder;
    color: red;
  }
  ul, li {
    list-style: none;
  }
</style>
{% endblock %}



{% block content %}

{% if request.user.is_authenticated %}
    <script>
        window.location.href = '{% url "users:profile" %}';
    </script>
{% endif %}
<div class="sign_up_body">
  <div class="container">
      <input type="checkbox" id="flip">
      <div class="cover">
        <div class="front">
          <img src="{% static 'passenger/images/frontImg.jpg'%}" alt="">
          <div class="text">
            <span class="text-1">Every new friend is a <br> new adventure</span>
            <span class="text-2">Let's get connected</span>
          </div>
        </div>
        <div class="back">
          <img class="backImg" src="{% static 'passenger/images/backImg.jpg' %}" alt="">
          <div class="text">
            <span class="text-1">Complete miles of journey <br> with one step</span>
            <span class="text-2">Let's get started</span>
          </div>
        </div>
      </div>
      <div class="forms">
          <div class="form-content">
            <div class="login-form">
              <div class="title">Reset Password</div>
            <form id="signinformw" method="post">
                {% if form.errors %}
                                <div class="alert alert-primary" role="alert">
                                    Error: Please check the two password and  try again!
                                </div>
                 {% endif %}
              {% csrf_token %}
              <div class="input-boxes">
                <div class="input-box">
                  <i class="fas fa-envelope"></i>
                  {{ form.new_password1 }}
                </div>
                <div class="input-box">
                  <i class="fas fa-lock"></i>
                  {{ form.new_password2 }}
                </div>
                <label class="check-container text">Show Passwords
                  <input type="checkbox" onclick="showPword()">
                  <span class="checkmark"></span>
                </label>

                <div class="text"><a href="{% url "users:pwdreset"%}">Forgot password?</a></div>

                <div class="button input-box">
                  <input type="submit" value="Submit">
                </div>

                <div class="text sign-up-text">Don't have an account? <a href="/users/sign-up/" class="label"> Signup now</a> <!--<label for="flip">Sigup now</label>--></div>
              </div>
              
          </form>
        </div>
        <div class="signup-form">
          </div>
      </div>
      </div>
    </div>
</div>

<script type="text/javascript">
  // Create a variable that can be used in main.js
  var recaptcha_site_key = '{{recaptcha_site_key|safe}}'
</script>
{% endblock%}

passenger/templates/user/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

passenger/templates/user/password_reset_form.html
{% extends 'home.html'%}
{% load static %}
{% block home_form_one%}
Reset password
{% endblock %}
{% block css_one %}
<link rel="stylesheet" href="{% static 'passenger/style.css'%}" />
{% endblock %}

{% block css_two %}
<style>
  .check_box {
    height: auto!important;
  }

  .alert {
    display: block;
    font-weight: bolder;
    color: red;
  }
  ul, li {
    list-style: none;
  }
</style>
{% endblock %}



{% block content %}


{% if request.user.is_authenticated %}
    <script>
        window.location.href = '{% url "users:profile" %}';
    </script>
{% endif %}


<div class="sign_up_body">
  <div class="container">
      <input type="checkbox" id="flip">
      <div class="cover">
        <div class="front">
          <img src="{% static 'passenger/images/frontImg.jpg'%}" alt="">
          <div class="text">
            <span class="text-1">Every new friend is a <br> new adventure</span>
            <span class="text-2">Let's get connected</span>
          </div>
        </div>
        <div class="back">
          <img class="backImg" src="{% static 'passenger/images/backImg.jpg' %}" alt="">
          <div class="text">
            <span class="text-1">Complete miles of journey <br> with one step</span>
            <span class="text-2">Let's get started</span>
          </div>
        </div>
      </div>
      <div class="forms">
          <div class="form-content">
            <div class="login-form">
              <div class="title">reset Password </div>
            <form action="{% url "users:pwdreset"%}" id="signinformw" method="POST">
              {% if form.errors %}

            <p>
              Please correct the following errors:
            </p>
            {% for field in form %}
            {% if field.errors %}
            <div class="alert">
              {{field.label}}: {{field.errors|striptags}}
            </div>
            {% endif %}
            {% endfor %}
            <p>
              if the error continues,please contact the admin
            </p>
            {% endif %}
              {% csrf_token %}
              <div class="input-boxes">
                <div class="input-box">
                  <i class="fas fa-envelope"></i>
                  {{form.email}}
                </div>

                <!--<div class="text"><a href="#">Forgot password?</a></div>-->

                <div class="button input-box">
                  <input type="submit" value="Send Email">
                </div>

                <div class="text sign-up-text">Don't have an account? <a href="/users/sign-up/" class="label"> Signup now</a> <!--<label for="flip">Sigup now</label>--></div>
              </div>
              
          </form>
        </div>
        <div class="signup-form">
          </div>
      </div>
      </div>
    </div>
</div>
{% endblock%}

passenger/templates/user/reset_status.html
{% if 'email' in request.get_full_path %}
<h3 class="mb-4">Password Reset Success</h3>
<p>Check your email for instructions</p>

<p> if you did not receive an email, your account is not active</p>
<p> contact the admin </p>
{% endif%}
{% if 'complete' in request.get_full_path %}
<h3 class="mb-4">Password Reset Success</h3>
<a href="{% url "users:sign-in" %}">Login</a>
{% endif%}

passenger/templates/user/sign_in.html
{% extends 'home.html'%}
{% load static %}
{% block css_one %}
<link rel="stylesheet" href="{% static 'passenger/style.css'%}" />
{% endblock %}

{% block css_two %}
<style>
  .check_box {
    height: auto!important;
  }

  .alert {
    display: block;
    font-weight: bolder;
    color: red;
  }
  ul, li {
    list-style: none;
  }
</style>
{% endblock %}



{% block content %}


<div class="sign_up_body">
  <div class="container">
      <input type="checkbox" id="flip">
      <div class="cover">
        <div class="front">
          <img src="{% static 'passenger/images/frontImg.jpg'%}" alt="">
          <div class="text">
            <span class="text-1">Every new friend is a <br> new adventure</span>
            <span class="text-2">Let's get connected</span>
          </div>
        </div>
        <div class="back">
          <img class="backImg" src="{% static 'passenger/images/backImg.jpg' %}" alt="">
          <div class="text">
            <span class="text-1">Complete miles of journey <br> with one step</span>
            <span class="text-2">Let's get started</span>
          </div>
        </div>
      </div>
      <div class="forms">
          <div class="form-content">
            <div class="login-form">
              <div class="title">Login</div>
            <form action="/users/sign-in/" id="signinformw" method="POST">
              {% if form.errors %}

            <p>
              Please correct the following errors:
            </p>
            <div class="alert">
              Error: Username or Password not correct!
            </div>
            <p>
              if the error continues,please contact the admin
            </p>
            {% endif %}
              {% csrf_token %}
              <div class="input-boxes">
                <div class="input-box">
                  <i class="fas fa-envelope"></i>
                  {{form.username}}
                </div>
                <div class="input-box">
                  <i class="fas fa-lock"></i>
                  {{form.password}}
                </div>
                <label class="check-container text">Show Passwords
                  <input type="checkbox" onclick="showPword()">
                  <span class="checkmark"></span>
                </label>

                <div class="text"><a href="{% url 'users:password_reset' %}">Forgot password?</a></div>

                <div class="button input-box">
                  <input type="submit" value="Submit">
                </div>

                <div class="text sign-up-text">Don't have an account? <a href="/users/sign-up/" class="label"> Signup now</a> <!--<label for="flip">Sigup now</label>--></div>
              </div>
              
          </form>
        </div>
        <div class="signup-form">
          </div>
      </div>
      </div>
    </div>
</div>

<script type="text/javascript">
  // Create a variable that can be used in main.js
  var recaptcha_site_key = '{{recaptcha_site_key|safe}}'
</script>
{% endblock%}